server:
  port: 9094

spring:
  profiles:
    active: dev
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27071/orderdb
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        enabled: true